version: '#{build}'
image: Visual Studio 2017

configuration: Release

environment:
  OPENCOVER_VER: 4.6.519
  COVERALLS_NET_VER: 0.412
  COVERAGE_FILTER: +[MiraclAuthentication.Core1.1]* -[MiraclAuthentication.Core1.1.Tests]* -[MiraclAuthenticationApp.Core1.1]* -[MiraclExternalAuthenticationApp.Core1.1]*
  COVERAGE_DIR: .\coverage
  OPENCOVER_EXE: '%COVERAGE_DIR%\OpenCover.%OPENCOVER_VER%\tools\OpenCover.Console.exe'
  COVERALLS_NET_EXE: '%COVERAGE_DIR%\coveralls.net.%COVERALLS_NET_VER%\tools\csmacnz.Coveralls.exe'
  COVERALLS_REPO_TOKEN:
    secure: wZSQgeaRONuhy2zczJuXQejHh/jXBNaaTfuFROv+RK4WPS2/ZIUG18lg7aynLXRb

install:
  - cmd: |
      nuget install OpenCover -Version %OPENCOVER_VER% -OutputDirectory %COVERAGE_DIR%
      nuget install coveralls.net -Version %COVERALLS_NET_VER% -OutputDirectory %COVERAGE_DIR%

before_build:
  - cmd: nuget restore

build:
  project: Authentication.sln
  verbosity: minimal

test_script:
  - cmd: |
      %OPENCOVER_EXE% -target:dotnet.exe -targetargs:"test -c Release MiraclAuthentication.Core1.1.Tests" -filter:"%COVERAGE_FILTER%" -register:user -oldStyle -output:%COVERAGE_DIR%\coverage.xml
      %COVERALLS_NET_EXE% --opencover -i %COVERAGE_DIR%\coverage.xml --serviceName appveyor --useRelativePaths
